#!/bin/bash

# Build script generated by tool
# Usage: ./build.sh [arguments...]

PROJECT_NAME="${PWD##*/}"
CC="${CC:-cc}"
DEBUG_FLAGS="-g -fsanitize=address,undefined"
WARN_FLAGS="-Wall -Wextra -Wpedantic -Wshadow -Wstrict-prototypes"

$CC src/*.c -Iinclude $WARN_FLAGS $DEBUG_FLAGS -o "$PROJECT_NAME" &&
./"$PROJECT_NAME" "$@"
